steps:
- name: node:16.13.1-alpine
  id: 'install'
  dir: 'functions'
  waitFor: ['-']
  entrypoint: 'npm'
  args: ['ci']
- name: node:16.13.1-alpine
  id: 'setup-environment'
  waitFor: ['install']
  dir: 'functions'
  entrypoint: 'firebase'
  args: [
    'functions:config:set', '--project=$PROJECT_ID',
    'calendly.access_token=',
    'calendly.base_url=',

    'mailchimp.api_key=',
    'mailchimp.server=',
    'mailchimp.default_list_id=',
    'mailchimp.career_list_id=',

    'sendgrid.api_key=',

    'contact_form.destination_email=',
    'career_form.destination_emails=',

    'recaptcha.secret_key=',

    'hubspot.api_key=',
    'hubspot.landing_deal_pipeline_name=',
    'hubspot.landing_deal_pipeline_stage=',
    'hubspot.blog_newsletter_id=',
  ]
- name: node:16.13.1-alpine
  waitFor: ['setup-environment']
  dir: 'functions'
  entrypoint: 'npm'
  args: ['run', 'deploy', '--project=$PROJECT_ID']

logsBucket: '$_LOGS_BUCKET'
timeout: 600s
options:
  logging: GCS_ONLY
