steps:
  - name: node:16.13.1-alpine
    id: "install"
    dir: "functions"
    waitFor: ["-"]
    entrypoint: "npm"
    args: ["ci"]
  - name: node:16.13.1-alpine
    id: "setup-firebase-json"
    dir: "functions"
    waitFor: ["-"]
    entrypoint: "sh"
    args: ["-c", "cat firebase-cloudbuild.json > firebase.json"]
  - name: gcr.io/$PROJECT_ID/firebase
    id: "setup-environment"
    waitFor: ["-"]
    dir: "functions"
    args:
      [
        "functions:config:set",
        "--project=$PROJECT_ID",
        "calendly.base_url=$_CF_CALENDLY_BASE_URL",
        "mailchimp.server=$_CF_MAILCHIMP_SERVER",
        "mailchimp.default_list_id=$_CF_MAILCHIMP_DEFAULT_LIST_ID",
        "mailchimp.career_list_id=$_CF_MAILCHIMP_CAREER_LIST_ID",
        "contact_form.destination_email=$_CF_CONTACT_FORM_DESTINATION_EMAIL",
        "career_form.destination_emails.0=$_CF_CAREER_FORM_DESTINATION_EMAILS",
        "hubspot.landing_deal_pipeline_name=$_CF_HUB_SPOT_LANDING_DEAL_PIPELINE_NAME",
        "hubspot.landing_deal_pipeline_stage=$_CF_HUB_SPOT_LANDING_DEAL_PIPELINE_STAGE",
        "hubspot.blog_newsletter_id=$_CF_HUB_SPOT_BLOG_NEWSLETTER_ID",
      ]
  - name: gcr.io/$PROJECT_ID/firebase
    dir: "functions"
    waitFor: ["setup-firebase-json", "setup-environment", "install"]
    args: ["deploy", "--project=$PROJECT_ID", "--only=functions"]

logsBucket: "$_LOGS_BUCKET"
timeout: 600s
options:
  logging: GCS_ONLY
