name: Deploy to Testing environment
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build-testing
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEDEVELOP_SITE_TESTING }}'
          channelId: live
          projectId: wedevelop-site-testing
          target: testing-2
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
