name: Deploy to Feature Testing environment
'on':
  push:
    branches:
      - feature/**
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2
      - run: npm ci && npm run build-testing
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEDEVELOP_SITE }}'
          projectId: wedevelop-site
          target: testing
          channelId: ${{ steps.extract_branch.outputs.branch }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
