name: Deploy to Feature Testing environment
'on':
  push:
    branches:
      - feature/**
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build-testing
        env:
          REACT_APP_PREVIEW_BUILD: feature
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEDEVELOP_SITE_TESTING }}'
          projectId: wedevelop-site-testing
          target: testing
          channelId: ${{ github.ref }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
