name: Deploy to Feature Testing environment
'on':
  push:
    branches:
      - feature/**
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build-testing
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEDEVELOP_SITE }}'
          projectId: wedevelop-site
          target: testing
          channelId: '${GITHUB_REF#refs/heads/}'
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
